name = "Beautiful Hugo"
license = "MIT"
licenselink = "https://github.com/TeamLinux01/beautifulhugo/blob/master/LICENSE"
description = "An adaptation of the Beautiful Jekyll theme"
tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "disqus", "light", "syntax highlighting", "multilingual", "portfolio", "projects", "mobile", "technical"]
features = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "disqus", "light", "syntax highlighting", "multilingual", "portfolio", "projects", "mobile", "technical"]
min_version = 0.48

[author]
    name = "Daniel Melzak"
    homepage = "https://daniel.melzaks.com"

# Base on updated theme
[fork]
    name = "halogenica"
    homepage = "https://halogenica.net"

# If Porting existing theme
[original]
    author =  "dattali"
    homepage = "https://beautifuljekyll.com"
    repo = "https://github.com/daattali/beautiful-jekyll"
